import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const user = null;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar user={user}/> */}
        {children}
      </body>
    </html>
  );
}
